apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: partner-onboarder      
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'