gitRepo:
  uri: https://github.com/PRGS-Puntland-Population-Register/mosip-config
  version: release-1.2.0.1
  ## Folders within the base repo where properties may be found.
  searchFolders: ""
  private: false
  ## User name of user who has access to the private repo. Ignore for public repo
  username: ""
  token: ""
