clusterDomain: cluster.local
logRetentionBytes: _1073741824
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
numPartitions: 20
replicaCount: 3
sidecars: {}
autoCreateTopicsEnable: true
# CAUTION: Option to delete topics should be disabled in production. 
deleteTopicEnable: true

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi

zookeeper:
  replicaCount: 3
  persistence:
    enabled: true
    size: 2Gi

resources:
  limits: 
   cpu: 2
   memory: 2Gi
  requests: 
    cpu: 200m
    memory: 256Mi

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30
  successThreshold: 1
