primary:
  extendedConfiguration: |
    max_connections=1000
    wal_level=logical
    max_wal_senders=20
    max_replication_slots=10
  resources:
    limits: 
     cpu: 2
     memory: 2Gi
    requests:
      cpu: 30m
      memory: 256Mi